name: test Couchbase Credential
on: [push]

jobs:
  test_credential:
    runs-on: ubuntu-latest
    name: Test that given env variable works
    steps:
      - run: wget https://github.com/couchbaselabs/couchbase-shell/releases/download/v0.75.1/cbsh-x86_64-unknown-linux-gnu.tar.gz
      - run: tar -xvzf cbsh-x86_64-unknown-linux-gnu.tar.gz
      - run: ./cbsh --username "$COUCHBASE_USERNAME" --connstr "$COUCHBASE_CONNECTION_STRING" -p "$COUCHBASE_PASSWORD" 
        shell: bash
        env:
          COUCHBASE_CONNECTION_STRING: ${{ secrets.COUCHBASE_CONNECTION_STRING }}
          COUCHBASE_USERNAME: ${{ secrets.COUCHBASE_USERNAME }}
          COUCHBASE_PASSWORD: ${{ secrets.COUCHBASE_PASSWORD }}
